# Generated by Django 5.0.4 on 2024-06-29 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostandfound',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='platform_management.address'),
        ),
    ]
